# _config.yml for corp.bjl13.com

# ---- Site Identity ----
title: BJL13 Enterprise Solutions LLC
description: >
  Corporate portal for BJL13 — breaking the chains of today to set tomorrow free.
  Legal, strategic, and governance documentation for partners, collaborators, and the public.
url: "https://corp.bjl13.com"
baseurl: ""  # Leave blank unless deploying in subdir

# ---- Theme ----
theme: null
remote_theme: pages-themes/modernist@v0.2.0

# ---- Plugins ----
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-redirect-from

# ---- Build & Content Settings ----
markdown: kramdown
highlighter: rouge
permalink: pretty

# ---- Author & Metadata ----
author: Brian J. London
email: info@bjl13.com
# twitter_username: bjl13org
github_username: bjl13

# ---- Defaults & Collections ----
defaults:
  - scope:
      path: ""
    values:
      layout: default
      sitemap: true
  - scope:
      path: "policies"
    values:
      layout: page
  - scope:
      path: "briefs"
    values:
      layout: page
  - scope:
      path: "internal"
    values:
      layout: internal
      sitemap: false

collections:
  policies:
    output: true
    permalink: /policies/:name/
  briefs:
    output: true
    permalink: /briefs/:name/
  internal:
    output: false

# ---- Navigation ----
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Policies
    url: /policies/
  - title: Briefs
    url: /briefs/
  - title: Contact
    url: /contact/

# ---- Branding ----
# These settings assume custom CSS is injected via assets/css/custom.css
# Colors: Deep purple header, teal brackets, coral highlights
sass:
  style: compressed

# ---- Exclusions ----
exclude:
  - README.md
  - LICENSE
  - Makefile
  - Gemfile
  - Gemfile.lock
  - node_modules
  - Dockerfile
  - "*.sh"
